// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PustokAppMvc.Data;

#nullable disable

namespace PustokAppMvc.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416192348_mig-2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PustokAppMvc.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000000"),
                            FullName = "Stephen King"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000000"),
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-0000-0000-000000000000"),
                            FullName = "George R.R. Martin"
                        });
                });

            modelBuilder.Entity("PustokAppMvc.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a1000000-0000-0000-0000-000000000000"),
                            Code = 1001,
                            Description = "A horror classic",
                            DiscountPercent = 10m,
                            HoverImageUrl = "image/products/product-2.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "image/products/product-1.jpg",
                            Name = "The Shining",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a2000000-0000-0000-0000-000000000000"),
                            Code = 1002,
                            Description = "Wizard boy",
                            DiscountPercent = 5m,
                            HoverImageUrl = "image/products/product-4.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "image/products/product-3.jpg",
                            Name = "Harry Potter and the Sorcerer's Stone",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a3000000-0000-0000-0000-000000000000"),
                            Code = 1003,
                            Description = "Winter is coming",
                            DiscountPercent = 0m,
                            HoverImageUrl = "image/products/product-6.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "image/products/product-5.jpg",
                            Name = "A Game of Thrones",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = new Guid("b4000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a1000000-0000-0000-0000-000000000000"),
                            Code = 1004,
                            Description = "Clown horror",
                            DiscountPercent = 15m,
                            HoverImageUrl = "image/products/product-8.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "image/products/product-7.jpg",
                            Name = "IT",
                            Price = 22.50m
                        },
                        new
                        {
                            Id = new Guid("b5000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a3000000-0000-0000-0000-000000000000"),
                            Code = 1005,
                            Description = "More winter",
                            DiscountPercent = 0m,
                            HoverImageUrl = "image/products/product-10.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = true,
                            MainImageUrl = "image/products/product-9.jpg",
                            Name = "A Clash of Kings",
                            Price = 28.00m
                        },
                        new
                        {
                            Id = new Guid("b6000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a2000000-0000-0000-0000-000000000000"),
                            Code = 1006,
                            Description = "Wizard boy 2",
                            DiscountPercent = 5m,
                            HoverImageUrl = "image/products/product-12.jpg",
                            InStock = false,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "image/products/product-11.jpg",
                            Name = "Harry Potter and the Chamber of Secrets",
                            Price = 26.00m
                        },
                        new
                        {
                            Id = new Guid("b7000000-0000-0000-0000-000000000000"),
                            AuthorId = new Guid("a1000000-0000-0000-0000-000000000000"),
                            Code = 1007,
                            Description = "Post-apocalyptic",
                            DiscountPercent = 20m,
                            HoverImageUrl = "image/products/product-1.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "image/products/product-13.jpg",
                            Name = "The Stand",
                            Price = 35.00m
                        });
                });

            modelBuilder.Entity("PustokAppMvc.Models.BookImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000000"),
                            BookId = new Guid("b1000000-0000-0000-0000-000000000000"),
                            ImageUrl = "image/products/product-details-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000000"),
                            BookId = new Guid("b1000000-0000-0000-0000-000000000000"),
                            ImageUrl = "image/products/product-details-2.jpg"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000000"),
                            BookId = new Guid("b2000000-0000-0000-0000-000000000000"),
                            ImageUrl = "image/products/product-details-3.jpg"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000000"),
                            BookId = new Guid("b3000000-0000-0000-0000-000000000000"),
                            ImageUrl = "image/products/product-details-4.jpg"
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000000"),
                            BookId = new Guid("b4000000-0000-0000-0000-000000000000"),
                            ImageUrl = "image/products/product-details-5.jpg"
                        });
                });

            modelBuilder.Entity("PustokAppMvc.Models.BookTag", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("b1000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b1000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b2000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b2000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c3000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b3000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b3000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c3000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b4000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b5000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c3000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b6000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c3000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b7000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            BookId = new Guid("b7000000-0000-0000-0000-000000000000"),
                            TagId = new Guid("c2000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PustokAppMvc.Models.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000000"),
                            ButtonText = "Shop Now",
                            ButtonUrl = "/books",
                            Description = "Get up to 50% discount",
                            ImageUrl = "image/bg-images/home-slider-1-ai.png",
                            Title = "Book Festival"
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000000"),
                            ButtonText = "Discover",
                            ButtonUrl = "/books",
                            Description = "Huge collections of new books",
                            ImageUrl = "image/bg-images/home-slider-2-ai.png",
                            Title = "Summer Sale"
                        });
                });

            modelBuilder.Entity("PustokAppMvc.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000000"),
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000000"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("c3000000-0000-0000-0000-000000000000"),
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("PustokAppMvc.Models.Book", b =>
                {
                    b.HasOne("PustokAppMvc.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PustokAppMvc.Models.BookImage", b =>
                {
                    b.HasOne("PustokAppMvc.Models.Book", "Book")
                        .WithMany("BookImages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PustokAppMvc.Models.Book", b =>
                {
                    b.Navigation("BookImages");
                });
#pragma warning restore 612, 618
        }
    }
}
